---                                                                                                                                                                                             
- name: Required Tools installation                                                                                                                                                             
  hosts: all                                                                                                                                                                                    
  become: yes                                                                                                                                                                                   
  become_user: root                                                                                                                                                                             
  tasks:                                                                                                                                                                                        
    - name: Install tools                                                                                                                                                                       
      yum:                                                                                                                                                                                      
        name: "{{ packages }}"                                                                                                                                                                  
      vars:                                                                                                                                                                                     
        packages:                                                                                                                                                                               
          - qperf                                                                                                                                                                               
          - nc                                                                                                                                                                                  
        state: latest                                                                                                                                                                           
    - name: Open firewall ports for required tools                                                                                                                                              
      firewalld:                                                                                                                                                                                
        port: 19765/tcp                                                                                                                                                                         
        permanent: no                                                                                                                                                                           
        immediate: yes                                                                                                                                                                          
        state: enabled                                                                                                                                                                          

- name: Allow network ports 
  hosts: new_nodes
  become: yes
  become_user: root
  vars:
    ports:
      - 53/tcp
      - 8053/tcp
      - 9200/tcp
      - 9300/tcp
      - 2049/tcp
      - 24007-24008/tcp
      - 24010/tcp
      - 3260/tcp
      - 111/tcp
      - 49152/tcp
      - 49664/tcp
      - 10250/tcp
      - 4789/udp
      - 8053/udp
      - 53/udp
  tasks:
    - name: Open required TCP port {{ ports }}
      firewalld:
        permanent: no
        immediate: yes
        state: enabled
        port: "{{ item }}"
      with_items: "{{ ports }}"

- name: Open network ports 
  hosts: new_nodes
  vars:
    ports:
      - 53
      - 8053
      - 9200
      - 9300
      - 2049
      - 24007
      - 24008
      - 24010
      - 3260
      - 111
      - 49152
      - 49664
      - 10250
      - 4789
      - 8053
      - 53
  become: yes
  become_user: root
  tasks:
    - name: Perform NC command to open a fake port
      #shell: echo hello | nc -l -p "{{ item }}"
      #shell: sh -c 'nc -l -p "{{ item }}"'
      shell: nohup nc -4lk "{{ item  }}" &
      with_items: "{{ ports }}"
