[masters]
host1.ansible-training.lab
host2.ansible-training.lab

[infras]

[new_nodes]
host3.ansible-training.lab

[ocs]

[all:children]
masters
infras
new_nodes
ocs

[source:children]
masters
infras
new_nodes


