---
- name: Check all udp ports
  hosts: new_nodes
  become: yes
  become_user: root
  vars:
    target:
      - host1.ansible-training.lab
      - host2.ansible-training.lab
    ports:
      - 22
      - 53
  tasks:
    - name: Open required UDP port 
      command: /usr/bin/nc -vz "{{ item.0 }}" "{{ item.1 }}"
      register: result
      with_nested: 
        - "{{ target }}"
        - "{{ ports }}"
    - debug:
        var: result 
