---                                                                                                                                                                                             
- name: Check all ports
  hosts: masters
  become: yes
  become_user: root
  vars:
    ports:
      - 22
  tasks:
    - name: Open required TCP port {{ ports }}
      command: /usr/bin/nc -vz host2.ansible-training.lab "{{ item  }}"
      register: result
      with_items: "{{ ports }}"
    - debug:
        var: result 
